# TerraX configuration file
# Save this file as .terrax.yaml in your project root or home directory

# Name of the root configuration file used to determine the project root directory
# This file is searched upward from the stack path to calculate relative paths in history
# Default: "root.hcl"
# Examples: "root.hcl", "terragrunt.hcl"
root_config_file: "root.hcl"

# List of Terragrunt commands to display in the TUI
# Default: ["plan", "apply", "validate", "fmt", "init", "output", "refresh", "destroy"]
commands:
  - plan # Show execution plan
  - apply # Apply infrastructure changes
  - validate # Validate configuration files
  - fmt # Format configuration files
  - init # Initialize working directory
  - output # Show output values
  - refresh # Refresh state
  - destroy # Destroy managed infrastructure

# Maximum number of navigation columns visible simultaneously
# Default: 3
# Minimum: 1
max_navigation_columns: 3

# History configuration
history:
  # Maximum number of execution history entries to keep
  # When the history exceeds this limit, older entries are automatically trimmed
  # Default: 500
  # Minimum: 10
  max_entries: 500

# Terragrunt configuration
# These settings control how terragrunt executes commands

# Logging configuration
# Log level for terragrunt output
# Options: "trace", "debug", "info", "warn", "error", "stdout", "stderr"
# Default: (terragrunt default)
log_level: "info"

# Log format for terragrunt output
# Options: "pretty", "bare", "key-value", "json"
# Default: "pretty"
# Note: This setting is ignored if log_custom_format is set
log_format: "pretty"

# Custom log format template for terragrunt output
# When set, this takes priority over log_format
# Default: (not set)
# Example: "%time %level %msg"
# Uncomment to use a custom format:
# log_custom_format: "%time %level %msg"

# Terragrunt execution flags
terragrunt:
  # Number of modules to run in parallel
  # Default: 0 (uses terragrunt's default parallelism)
  # Set to a positive number to limit parallelism
  # parallelism: 4

  # Disable colored output
  # Default: false
  # no_color: true

  # Run in non-interactive mode (no prompts)
  # Default: false
  # non_interactive: true

  # Include external dependencies in queue
  # Default: false
  # queue_include_external: true

  # Ignore dependency errors and continue execution
  # Default: false
  # ignore_dependency_errors: true

  # Ignore external dependencies (dependencies outside the working directory)
  # Default: false
  # ignore_external_dependencies: true

  # Include external dependencies in execution
  # Default: false
  # include_external_dependencies: true

  # Additional custom flags to pass to terragrunt
  # This is a list of flags that will be added to every command
  # Useful for flags not explicitly supported above
  # Example:
  # extra_flags:
  #   - "--terragrunt-download-dir=/tmp/terragrunt"
  #   - "--terragrunt-source-update"
