name: "Setup Go Environment"
description: "Setup Go and install project dependencies"
inputs:
  go-version:
    description: "Go version to install"
    required: false
    default: "1.25"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install dependencies
      shell: bash
      run: go mod download

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
